apiVersion: v1
kind: Pod
metadata:
  name: "fiap-mongodb-pod"
  labels: 
    app: "fiap-mongodb-pod"
spec:
  containers: 
    - name: fiap-mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "AOjtR096G3l"
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db  

  volumes:
    - name: mongodb-data
      emptyDir: {}  