apiVersion: v1
kind: Service
metadata:
  name: fiap-loadbalancer-service
spec:
  selector:
    app: fiap-apis-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: LoadBalancer